package Model;
// Generated 29-may-2019 19:08:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aprendiz generated by hbm2java
 */
public class Aprendiz  implements java.io.Serializable {


     private Integer idAprendiz;
     private Usuario usuario;
     private Set<AprendizFicha> aprendizFichas = new HashSet<AprendizFicha>(0);

    public Aprendiz() {
    }

	
    public Aprendiz(Usuario usuario) {
        this.usuario = usuario;
    }
    public Aprendiz(Usuario usuario, Set<AprendizFicha> aprendizFichas) {
       this.usuario = usuario;
       this.aprendizFichas = aprendizFichas;
    }
   
    public Integer getIdAprendiz() {
        return this.idAprendiz;
    }
    
    public void setIdAprendiz(Integer idAprendiz) {
        this.idAprendiz = idAprendiz;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Set<AprendizFicha> getAprendizFichas() {
        return this.aprendizFichas;
    }
    
    public void setAprendizFichas(Set<AprendizFicha> aprendizFichas) {
        this.aprendizFichas = aprendizFichas;
    }




}


