package Model;
// Generated 29-may-2019 19:08:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AprendizFicha generated by hbm2java
 */
public class AprendizFicha  implements java.io.Serializable {


     private Integer idAprendizFicha;
     private Aprendiz aprendiz;
     private Ficha ficha;
     private Date fechaRegistro;
     private Date fechaModificacio;
     private Integer idUsuarioModifica;
     private String nombreUsuarioModifica;

    public AprendizFicha() {
    }

	
    public AprendizFicha(Aprendiz aprendiz, Ficha ficha) {
        this.aprendiz = aprendiz;
        this.ficha = ficha;
    }
    public AprendizFicha(Aprendiz aprendiz, Ficha ficha, Date fechaRegistro, Date fechaModificacio, Integer idUsuarioModifica, String nombreUsuarioModifica) {
       this.aprendiz = aprendiz;
       this.ficha = ficha;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacio = fechaModificacio;
       this.idUsuarioModifica = idUsuarioModifica;
       this.nombreUsuarioModifica = nombreUsuarioModifica;
    }
   
    public Integer getIdAprendizFicha() {
        return this.idAprendizFicha;
    }
    
    public void setIdAprendizFicha(Integer idAprendizFicha) {
        this.idAprendizFicha = idAprendizFicha;
    }
    public Aprendiz getAprendiz() {
        return this.aprendiz;
    }
    
    public void setAprendiz(Aprendiz aprendiz) {
        this.aprendiz = aprendiz;
    }
    public Ficha getFicha() {
        return this.ficha;
    }
    
    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacio() {
        return this.fechaModificacio;
    }
    
    public void setFechaModificacio(Date fechaModificacio) {
        this.fechaModificacio = fechaModificacio;
    }
    public Integer getIdUsuarioModifica() {
        return this.idUsuarioModifica;
    }
    
    public void setIdUsuarioModifica(Integer idUsuarioModifica) {
        this.idUsuarioModifica = idUsuarioModifica;
    }
    public String getNombreUsuarioModifica() {
        return this.nombreUsuarioModifica;
    }
    
    public void setNombreUsuarioModifica(String nombreUsuarioModifica) {
        this.nombreUsuarioModifica = nombreUsuarioModifica;
    }




}


