package Model;
// Generated 29-may-2019 19:08:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EvidenciaAprendizaje generated by hbm2java
 */
public class EvidenciaAprendizaje  implements java.io.Serializable {


     private Integer idEvidencia;
     private ResultadoAprendizaje resultadoAprendizaje;
     private String nombreEvidencia;
     private String descripcionEvidencia;
     private Date fechaInicio;
     private Date fechaFin;
     private Date fechaRegistro;
     private Set<JuicioEvalutivo> juicioEvalutivos = new HashSet<JuicioEvalutivo>(0);

    public EvidenciaAprendizaje() {
    }

	
    public EvidenciaAprendizaje(ResultadoAprendizaje resultadoAprendizaje, String nombreEvidencia) {
        this.resultadoAprendizaje = resultadoAprendizaje;
        this.nombreEvidencia = nombreEvidencia;
    }
    public EvidenciaAprendizaje(ResultadoAprendizaje resultadoAprendizaje, String nombreEvidencia, String descripcionEvidencia, Date fechaInicio, Date fechaFin, Date fechaRegistro, Set<JuicioEvalutivo> juicioEvalutivos) {
       this.resultadoAprendizaje = resultadoAprendizaje;
       this.nombreEvidencia = nombreEvidencia;
       this.descripcionEvidencia = descripcionEvidencia;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.fechaRegistro = fechaRegistro;
       this.juicioEvalutivos = juicioEvalutivos;
    }
   
    public Integer getIdEvidencia() {
        return this.idEvidencia;
    }
    
    public void setIdEvidencia(Integer idEvidencia) {
        this.idEvidencia = idEvidencia;
    }
    public ResultadoAprendizaje getResultadoAprendizaje() {
        return this.resultadoAprendizaje;
    }
    
    public void setResultadoAprendizaje(ResultadoAprendizaje resultadoAprendizaje) {
        this.resultadoAprendizaje = resultadoAprendizaje;
    }
    public String getNombreEvidencia() {
        return this.nombreEvidencia;
    }
    
    public void setNombreEvidencia(String nombreEvidencia) {
        this.nombreEvidencia = nombreEvidencia;
    }
    public String getDescripcionEvidencia() {
        return this.descripcionEvidencia;
    }
    
    public void setDescripcionEvidencia(String descripcionEvidencia) {
        this.descripcionEvidencia = descripcionEvidencia;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<JuicioEvalutivo> getJuicioEvalutivos() {
        return this.juicioEvalutivos;
    }
    
    public void setJuicioEvalutivos(Set<JuicioEvalutivo> juicioEvalutivos) {
        this.juicioEvalutivos = juicioEvalutivos;
    }




}


