package Model;
// Generated 29-may-2019 19:08:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ficha generated by hbm2java
 */
public class Ficha  implements java.io.Serializable {


     private Integer idFicha;
     private ProgramaDeFormacion programaDeFormacion;
     private int cupo;
     private Date fechaRegistro;
     private Set<Trimestre> trimestres = new HashSet<Trimestre>(0);
     private Set<AprendizFicha> aprendizFichas = new HashSet<AprendizFicha>(0);

    public Ficha() {
    }

	
    public Ficha(ProgramaDeFormacion programaDeFormacion, int cupo, Date fechaRegistro) {
        this.programaDeFormacion = programaDeFormacion;
        this.cupo = cupo;
        this.fechaRegistro = fechaRegistro;
    }
    public Ficha(ProgramaDeFormacion programaDeFormacion, int cupo, Date fechaRegistro, Set<Trimestre> trimestres, Set<AprendizFicha> aprendizFichas) {
       this.programaDeFormacion = programaDeFormacion;
       this.cupo = cupo;
       this.fechaRegistro = fechaRegistro;
       this.trimestres = trimestres;
       this.aprendizFichas = aprendizFichas;
    }
   
    public Integer getIdFicha() {
        return this.idFicha;
    }
    
    public void setIdFicha(Integer idFicha) {
        this.idFicha = idFicha;
    }
    public ProgramaDeFormacion getProgramaDeFormacion() {
        return this.programaDeFormacion;
    }
    
    public void setProgramaDeFormacion(ProgramaDeFormacion programaDeFormacion) {
        this.programaDeFormacion = programaDeFormacion;
    }
    public int getCupo() {
        return this.cupo;
    }
    
    public void setCupo(int cupo) {
        this.cupo = cupo;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Trimestre> getTrimestres() {
        return this.trimestres;
    }
    
    public void setTrimestres(Set<Trimestre> trimestres) {
        this.trimestres = trimestres;
    }
    public Set<AprendizFicha> getAprendizFichas() {
        return this.aprendizFichas;
    }
    
    public void setAprendizFichas(Set<AprendizFicha> aprendizFichas) {
        this.aprendizFichas = aprendizFichas;
    }




}


