package Model;
// Generated 29-may-2019 19:08:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Instructor generated by hbm2java
 */
public class Instructor  implements java.io.Serializable {


     private Integer idInstructor;
     private Usuario usuario;
     private Set<InstructorResultadoAprendizaje> instructorResultadoAprendizajes = new HashSet<InstructorResultadoAprendizaje>(0);

    public Instructor() {
    }

	
    public Instructor(Usuario usuario) {
        this.usuario = usuario;
    }
    public Instructor(Usuario usuario, Set<InstructorResultadoAprendizaje> instructorResultadoAprendizajes) {
       this.usuario = usuario;
       this.instructorResultadoAprendizajes = instructorResultadoAprendizajes;
    }
   
    public Integer getIdInstructor() {
        return this.idInstructor;
    }
    
    public void setIdInstructor(Integer idInstructor) {
        this.idInstructor = idInstructor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Set<InstructorResultadoAprendizaje> getInstructorResultadoAprendizajes() {
        return this.instructorResultadoAprendizajes;
    }
    
    public void setInstructorResultadoAprendizajes(Set<InstructorResultadoAprendizaje> instructorResultadoAprendizajes) {
        this.instructorResultadoAprendizajes = instructorResultadoAprendizajes;
    }




}


