package Model;
// Generated 29-may-2019 19:08:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * InstructorResultadoAprendizaje generated by hbm2java
 */
public class InstructorResultadoAprendizaje  implements java.io.Serializable {


     private Integer idInstructorResultadoAprendizaje;
     private Instructor instructor;
     private ResultadoAprendizaje resultadoAprendizaje;
     private Date fechaRegistro;
     private Date fechaModificacio;
     private Integer idUsuarioModifica;
     private String nombreUsuarioModifica;

    public InstructorResultadoAprendizaje() {
    }

	
    public InstructorResultadoAprendizaje(Instructor instructor, ResultadoAprendizaje resultadoAprendizaje) {
        this.instructor = instructor;
        this.resultadoAprendizaje = resultadoAprendizaje;
    }
    public InstructorResultadoAprendizaje(Instructor instructor, ResultadoAprendizaje resultadoAprendizaje, Date fechaRegistro, Date fechaModificacio, Integer idUsuarioModifica, String nombreUsuarioModifica) {
       this.instructor = instructor;
       this.resultadoAprendizaje = resultadoAprendizaje;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacio = fechaModificacio;
       this.idUsuarioModifica = idUsuarioModifica;
       this.nombreUsuarioModifica = nombreUsuarioModifica;
    }
   
    public Integer getIdInstructorResultadoAprendizaje() {
        return this.idInstructorResultadoAprendizaje;
    }
    
    public void setIdInstructorResultadoAprendizaje(Integer idInstructorResultadoAprendizaje) {
        this.idInstructorResultadoAprendizaje = idInstructorResultadoAprendizaje;
    }
    public Instructor getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }
    public ResultadoAprendizaje getResultadoAprendizaje() {
        return this.resultadoAprendizaje;
    }
    
    public void setResultadoAprendizaje(ResultadoAprendizaje resultadoAprendizaje) {
        this.resultadoAprendizaje = resultadoAprendizaje;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacio() {
        return this.fechaModificacio;
    }
    
    public void setFechaModificacio(Date fechaModificacio) {
        this.fechaModificacio = fechaModificacio;
    }
    public Integer getIdUsuarioModifica() {
        return this.idUsuarioModifica;
    }
    
    public void setIdUsuarioModifica(Integer idUsuarioModifica) {
        this.idUsuarioModifica = idUsuarioModifica;
    }
    public String getNombreUsuarioModifica() {
        return this.nombreUsuarioModifica;
    }
    
    public void setNombreUsuarioModifica(String nombreUsuarioModifica) {
        this.nombreUsuarioModifica = nombreUsuarioModifica;
    }




}


