package Model;
// Generated 29-may-2019 19:08:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private Integer idPermiso;
     private Rol rol;
     private String nombrePermiso;
     private String modulo;
     private String estado;
     private boolean crar;
     private boolean consultar;
     private boolean modificar;
     private boolean eliminar;
     private Date fechaModificacio;
     private Integer idUsuarioModifica;
     private String nombreUsuarioModifica;

    public Permiso() {
    }

	
    public Permiso(Rol rol, String modulo, String estado, boolean crar, boolean consultar, boolean modificar, boolean eliminar) {
        this.rol = rol;
        this.modulo = modulo;
        this.estado = estado;
        this.crar = crar;
        this.consultar = consultar;
        this.modificar = modificar;
        this.eliminar = eliminar;
    }
    public Permiso(Rol rol, String nombrePermiso, String modulo, String estado, boolean crar, boolean consultar, boolean modificar, boolean eliminar, Date fechaModificacio, Integer idUsuarioModifica, String nombreUsuarioModifica) {
       this.rol = rol;
       this.nombrePermiso = nombrePermiso;
       this.modulo = modulo;
       this.estado = estado;
       this.crar = crar;
       this.consultar = consultar;
       this.modificar = modificar;
       this.eliminar = eliminar;
       this.fechaModificacio = fechaModificacio;
       this.idUsuarioModifica = idUsuarioModifica;
       this.nombreUsuarioModifica = nombreUsuarioModifica;
    }
   
    public Integer getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(Integer idPermiso) {
        this.idPermiso = idPermiso;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getNombrePermiso() {
        return this.nombrePermiso;
    }
    
    public void setNombrePermiso(String nombrePermiso) {
        this.nombrePermiso = nombrePermiso;
    }
    public String getModulo() {
        return this.modulo;
    }
    
    public void setModulo(String modulo) {
        this.modulo = modulo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public boolean isCrar() {
        return this.crar;
    }
    
    public void setCrar(boolean crar) {
        this.crar = crar;
    }
    public boolean isConsultar() {
        return this.consultar;
    }
    
    public void setConsultar(boolean consultar) {
        this.consultar = consultar;
    }
    public boolean isModificar() {
        return this.modificar;
    }
    
    public void setModificar(boolean modificar) {
        this.modificar = modificar;
    }
    public boolean isEliminar() {
        return this.eliminar;
    }
    
    public void setEliminar(boolean eliminar) {
        this.eliminar = eliminar;
    }
    public Date getFechaModificacio() {
        return this.fechaModificacio;
    }
    
    public void setFechaModificacio(Date fechaModificacio) {
        this.fechaModificacio = fechaModificacio;
    }
    public Integer getIdUsuarioModifica() {
        return this.idUsuarioModifica;
    }
    
    public void setIdUsuarioModifica(Integer idUsuarioModifica) {
        this.idUsuarioModifica = idUsuarioModifica;
    }
    public String getNombreUsuarioModifica() {
        return this.nombreUsuarioModifica;
    }
    
    public void setNombreUsuarioModifica(String nombreUsuarioModifica) {
        this.nombreUsuarioModifica = nombreUsuarioModifica;
    }




}


