package Model;
// Generated 29-may-2019 19:08:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String numeroDocumento;
     private String tipoDocumento;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private String genero;
     private String correo;
     private Date fechaModificacio;
     private Integer idUsuarioModifica;
     private String nombreUsuarioModifica;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Persona() {
    }

	
    public Persona(String numeroDocumento, String tipoDocumento, String primerNombre, String primerApellido) {
        this.numeroDocumento = numeroDocumento;
        this.tipoDocumento = tipoDocumento;
        this.primerNombre = primerNombre;
        this.primerApellido = primerApellido;
    }
    public Persona(String numeroDocumento, String tipoDocumento, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, String genero, String correo, Date fechaModificacio, Integer idUsuarioModifica, String nombreUsuarioModifica, Set<Usuario> usuarios) {
       this.numeroDocumento = numeroDocumento;
       this.tipoDocumento = tipoDocumento;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.genero = genero;
       this.correo = correo;
       this.fechaModificacio = fechaModificacio;
       this.idUsuarioModifica = idUsuarioModifica;
       this.nombreUsuarioModifica = nombreUsuarioModifica;
       this.usuarios = usuarios;
    }
   
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Date getFechaModificacio() {
        return this.fechaModificacio;
    }
    
    public void setFechaModificacio(Date fechaModificacio) {
        this.fechaModificacio = fechaModificacio;
    }
    public Integer getIdUsuarioModifica() {
        return this.idUsuarioModifica;
    }
    
    public void setIdUsuarioModifica(Integer idUsuarioModifica) {
        this.idUsuarioModifica = idUsuarioModifica;
    }
    public String getNombreUsuarioModifica() {
        return this.nombreUsuarioModifica;
    }
    
    public void setNombreUsuarioModifica(String nombreUsuarioModifica) {
        this.nombreUsuarioModifica = nombreUsuarioModifica;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


