package Model;
// Generated 29-may-2019 19:08:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String nombreRol;
     private String descripcion;
     private String estado;
     private Date fechaRegistro;
     private Integer idUsuarioModifica;
     private String nombreUsuarioModifica;
     private Set<Perfil> perfils = new HashSet<Perfil>(0);
     private Set<Permiso> permisos = new HashSet<Permiso>(0);

    public Rol() {
    }

	
    public Rol(String nombreRol, String descripcion, String estado) {
        this.nombreRol = nombreRol;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public Rol(String nombreRol, String descripcion, String estado, Date fechaRegistro, Integer idUsuarioModifica, String nombreUsuarioModifica, Set<Perfil> perfils, Set<Permiso> permisos) {
       this.nombreRol = nombreRol;
       this.descripcion = descripcion;
       this.estado = estado;
       this.fechaRegistro = fechaRegistro;
       this.idUsuarioModifica = idUsuarioModifica;
       this.nombreUsuarioModifica = nombreUsuarioModifica;
       this.perfils = perfils;
       this.permisos = permisos;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Integer getIdUsuarioModifica() {
        return this.idUsuarioModifica;
    }
    
    public void setIdUsuarioModifica(Integer idUsuarioModifica) {
        this.idUsuarioModifica = idUsuarioModifica;
    }
    public String getNombreUsuarioModifica() {
        return this.nombreUsuarioModifica;
    }
    
    public void setNombreUsuarioModifica(String nombreUsuarioModifica) {
        this.nombreUsuarioModifica = nombreUsuarioModifica;
    }
    public Set<Perfil> getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set<Perfil> perfils) {
        this.perfils = perfils;
    }
    public Set<Permiso> getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set<Permiso> permisos) {
        this.permisos = permisos;
    }




}


